/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/IdTclh7Sard
 */
import { CardTitle, CardDescription, CardContent, CardFooter, Card } from "@/components/common/ui/card"
import { Button } from "@/components/common/ui/button"

export function y() {
  return (
    (<Card key="1">
      <CardContent className="mt-1">
        <img
          alt="Placeholder image"
          className="object-cover w-full h-64"
          height="200"
          src="/placeholder.svg"
          style={{
            aspectRatio: "200/200",
            objectFit: "cover",
          }}
          width="200" />
        <CardTitle className="text-lg font-semibold mt-1">Title</CardTitle>
        <CardDescription className="text-base text-gray-500 dark:text-gray-400 mt-1">
          Description for the card.
        </CardDescription>
      </CardContent>
      <CardFooter className="mt-2">
        <Button variant="default">Click Me</Button>
      </CardFooter>
    </Card>)
  );
}
